version: '3'
services:
  mysql:
    image: mysql:5.5.42
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=sysstate
      - MYSQL_USER=sysstate
      - MYSQL_PASSWORD=sysstate
  server1:
    build: sysstate-server
    ports:
      - "8080:8080"
    environment:
      - db.connectURI=jdbc:mysql://mysql:3306/sysstate?autoReconnect=true
      - db.userName=sysstate
      - db.password=sysstate
      - hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - db.driver=com.mysql.jdbc.Driver
      - hibernate.strategy=update
      - work.node=001
    links:
      - "mysql:mysql"
  server2:
    build: sysstate-server
    depends_on: 
      - server1
    ports:
      - "8180:8080"
    environment:
      - db.connectURI=jdbc:mysql://mysql:3306/sysstate?autoReconnect=true
      - db.userName=sysstate
      - db.password=sysstate
      - hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - db.driver=com.mysql.jdbc.Driver
      - hibernate.strategy=validate
      - work.node=002
    links:
      - "mysql:mysql"


#  volumes:
#    - "~/sysstate/home:/usr/local/tomcat/.sysstate"



